export interface VocabTerm {
  label: string
  keywords: string[]
}

function term(label: string, keywords: string[] = []): VocabTerm {
  return { label, keywords: [label.toLowerCase(), ...keywords.map((k) => k.toLowerCase())] }
}

export const symptomOptions: VocabTerm[] = [
  term('Pain', ['painful', 'ache']),
  term('Pain with eye movement', ['pain on eye movement']),
  term('Photophobia', ['light sensitivity']),
  term('Redness', ['red eye', 'injection', 'hyperemia', 'flush']),
  term('Itching', ['itchy', 'pruritus']),
  term('Burning', ['burning sensation']),
  term('Dryness', ['dry eye']),
  term('Discharge', ['purulent', 'mucopurulent', 'watery discharge']),
  term('Crusting/matted lashes', ['crusting', 'matted lashes', 'matted']),
  term('Tearing', ['epiphora']),
  term('Decreased vision', ['blurred vision', 'vision loss', 'reduced vision', 'blur']),
  term('Sudden vision loss', ['sudden loss of vision', 'acute vision loss']),
  term('Gradual/progressive vision loss', ['gradual vision loss', 'progressive vision loss']),
  term('Peripheral vision loss', ['visual field loss', 'tunnel vision', 'peripheral vision loss']),
  term('Fluctuating vision', ['vision fluctuates', 'variable vision']),
  term('Night vision difficulty', ['night blindness', 'nyctalopia']),
  term('Glare/halos around lights', ['glare', 'halos']),
  term('Diplopia', ['double vision']),
  term('Floaters', []),
  term('Flashes', ['photopsia']),
  term('Headache', []),
  term('Nausea/vomiting', ['nausea', 'vomiting']),
  term('Metamorphopsia', ['distorted vision', 'distortion']),
  term('Foreign body sensation', ['gritty', 'sandy sensation', 'fb sensation']),
  term('Eyelid swelling', ['lid swelling', 'periorbital swelling', 'lid edema']),
  term('Ptosis (drooping eyelid)', ['ptosis', 'drooping eyelid']),
  term('Eye turn noticed', ['eye turn', 'strabismus', 'crossed eyes', 'wandering eye']),
  term('Eye strain', ['asthenopia', 'eye fatigue']),
]

export const pupilOptions: VocabTerm[] = [
  term('Anisocoria', []),
  term('RAPD', ['relative afferent pupillary defect', 'afferent pupillary defect']),
  term('Irregular pupil', []),
  term('Poor reaction', ['poorly reactive', 'sluggish pupil']),
  term('Miosis', ['constricted pupil', 'small pupil']),
  term('Mydriasis', ['dilated pupil', 'large pupil']),
  term('Light-near dissociation', []),
  term('Tonic pupil', ['adie pupil', 'tonic redilation']),
]

export const anteriorSegmentOptions: VocabTerm[] = [
  term('Corneal opacity', ['scarring', 'scar']),
  term('Corneal infiltrate', ['stromal infiltrate']),
  term('Corneal epithelial defect', ['epithelial defect', 'dendritic']),
  term('Corneal edema', ['stromal edema']),
  term('Corneal neovascularization', ['vascularization', 'pannus']),
  term('Corneal thinning/ectasia', ['thinning', 'ectasia']),
  term('Punctate epithelial keratopathy', ['punctate epithelial', 'punctate keratopathy']),
  term('Corneal ulcer', ['ulcer']),
  term('Corneal filaments', ['corneal filament']),
  term('Descemet membrane changes', ['descemet']),
  term('Endothelial guttae', ['guttae', 'guttata', 'endothelial']),
  term('Band keratopathy', ['band keratopathy', 'calcific plaque']),
  term('Pterygium/pinguecula', ['pterygium', 'pinguecula']),
  term('Corneal foreign body', ['foreign body', 'rust ring']),
  term('Keratic precipitates', ['kp']),
  term('Anterior chamber cells', ['ac cells', 'cell and flare']),
  term('Anterior chamber flare', ['flare']),
  term('Shallow anterior chamber', ['shallow anterior chamber', 'shallow ac']),
  term('Deep anterior chamber', ['deep anterior chamber']),
  term('Hypopyon', []),
  term('Hyphema', []),
  term('Ciliary flush', []),
  term('Conjunctival injection', ['injection']),
  term('Chemosis', []),
  term('Follicles', ['follicular reaction', 'follicles']),
  term('Papillae', ['papillae', 'papillary reaction', 'giant papillae', 'cobblestone']),
  term('Pseudomembrane', ['pseudomembrane', 'membrane']),
  term('Symblepharon', []),
  term('Abnormal iris', ['iris atrophy', 'posterior synechiae']),
  term('Iris nodules', ['iris nodule', 'koeppe', 'busacca']),
  term('Iris/angle neovascularization', ['rubeosis', 'iris neovascularization', 'nvi']),
  term('Lens opacity', ['cataract', 'lens opacification']),
  term('Lens subluxation/dislocation', ['subluxation', 'dislocated lens', 'ectopia lentis']),
  term('Lid retraction/lagophthalmos', ['lid retraction', 'lagophthalmos']),
  term('Trichiasis/distichiasis', ['trichiasis', 'distichiasis']),
  term('Proptosis', ['exophthalmos']),
  term('Vesicular/dermatomal rash', ['vesicular rash', 'dermatomal']),
]

export const posteriorSegmentOptions: VocabTerm[] = [
  term('Disc edema', ['optic disc swelling', 'papilledema']),
  term('Disc pallor/atrophy', ['pallor', 'optic atrophy']),
  term('Disc hemorrhage', ['disc hemorrhage', 'peripapillary hemorrhage']),
  term('Increased C/D ratio', ['cupping', 'cup to disc']),
  term('Hemorrhage', ['flame hemorrhage', 'dot blot hemorrhage', 'retinal hemorrhage']),
  term('Microaneurysms', ['microaneurysm']),
  term('Venous beading', []),
  term('Retinal/disc neovascularization', ['neovascularization', 'nvd', 'nve']),
  term('Drusen', []),
  term('Exudates', ['hard exudates']),
  term('Cotton-wool spots', []),
  term('Roth spots', ['roth spot']),
  term('Macular edema', []),
  term('Macular hole', []),
  term('Epiretinal membrane', ['epiretinal membrane', 'macular pucker']),
  term('Subretinal fluid', []),
  term('Retinal/chorioretinal scar or atrophy', ['chorioretinal scar', 'chorioretinitis', 'chorioretinal atrophy']),
  term('Choroidal nevus/mass', ['choroidal nevus', 'choroidal mass', 'pigmented lesion']),
  term('Pigmentary changes (bone spicule)', ['bone-spicule', 'bone spicule', 'pigmentary retinopathy']),
  term('Lattice degeneration', []),
  term('Retinoschisis', []),
  term('Retinal tear', []),
  term('Retinal detachment', ['detached retina']),
  term('Vitreous hemorrhage', []),
  term('Vitreous cells/haze', ['vitreous cell', 'vitritis', 'vitreous haze']),
  term('Posterior vitreous detachment', ['pvd', 'weiss ring']),
]

export const visualFieldOptions: VocabTerm[] = [
  term('Central scotoma', []),
  term('Paracentral scotoma', []),
  term('Cecocentral scotoma', []),
  term('Altitudinal defect', []),
  term('Arcuate defect', []),
  term('Nasal step', []),
  term('Generalized/diffuse constriction', ['generalized depression', 'diffuse field loss', 'constricted field', 'tunnel vision']),
  term('Bitemporal hemianopia', []),
  term('Homonymous hemianopia', []),
  term('Quadrantanopia', ['quadrantanopsia']),
  term('Enlarged blind spot', []),
]

export const otherTestingOptions: VocabTerm[] = [
  term('OCT findings', ['oct']),
  term('Topography findings', ['topography']),
  term('Pachymetry', ['thin cornea', 'thinning']),
  term('Gonioscopy', ['angle']),
  term('B-scan ultrasound', ['b-scan', 'ultrasound']),
  term('Fluorescein angiography', ['fluorescein angiography', 'fa pattern']),
  term('Electroretinogram/EOG', ['electroretinogram', 'erg', 'eog']),
  term('Visual evoked potential', ['visual evoked potential', 'vep']),
  term('Color vision', ['dyschromatopsia']),
  term('Amsler grid', []),
  term('Fluorescein staining', ['staining']),
  term('Schirmer test', ['schirmer']),
  term('Tear breakup time', ['tear breakup time', 'tbut']),
  term('Motility findings', ['restricted motility', 'diplopia on gaze']),
  term('Cover test findings', ['cover test']),
  term('Forced duction test', ['forced duction']),
]
